Sprint2
ClevertecFrontendLab/sprint2-Anastasiya1982 pull request #1
Opened 2023-02-06 15:22 UTC by Anastasiya1982

1. не сделан скролл на ховер,  но скидываю заранее чтоб успеть исправить  остальные замечания до окончания спринта. заранее благоданость)

2023-02-06 15:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675697177/slider%20one%20foto%20768px.png)

2023-02-06 16:11 UTC, SergeyGlazun requested changes

2023-02-06 16:11 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
>  import { Swiper, SwiperSlide } from 'swiper/react';
![image](https://user-images.githubusercontent.com/70904466/217022984-c0b67fee-cc2d-4867-b455-3c654453660c.png)

2023-02-06 16:11 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
> -import SwiperCore, { FreeMode, Thumbs, Navigation, Scrollbar, Pagination } from 'swiper';
![image](https://user-images.githubusercontent.com/70904466/217023584-5177a1de-d13f-4227-97b6-68e8a6a57321.png)
тут тоже нужно переключаться при нажатии

2023-02-06 16:11 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
> +import { FreeMode, Thumbs, Navigation, Pagination, Scrollbar, Mousewheel } from 'swiper';
![image](https://user-images.githubusercontent.com/70904466/217023867-5ecee2cb-41c1-4e57-869a-fa75ab7ae638.png)
при переходе на книгу в некоторых книгах пустой экран

2023-02-06 17:16 UTC, Anastasiya1982 commented on src/components/book-preview/book-preview.jsx
>  import { Swiper, SwiperSlide } from 'swiper/react';
done

2023-02-06 17:17 UTC, Anastasiya1982 commented on src/components/book-preview/book-preview.jsx
> -import SwiperCore, { FreeMode, Thumbs, Navigation, Scrollbar, Pagination } from 'swiper';
пееделала

2023-02-06 17:37 UTC, Anastasiya1982 commented on src/components/book-preview/book-preview.jsx
> +import { FreeMode, Thumbs, Navigation, Pagination, Scrollbar, Mousewheel } from 'swiper';
исправила... картинки просто с нета грузятся пока

2023-02-06 19:20 UTC, SergeyGlazun requested changes

2023-02-06 19:20 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
>  import { useState } from 'react';
![image](https://user-images.githubusercontent.com/70904466/217064602-212ce971-edb6-4f36-b191-7ea26d6fe4ad.png)

2023-02-06 19:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675711588/slider%20one%20foto%20768px.png)

2023-02-06 19:38 UTC, SergeyGlazun requested changes

2023-02-06 19:38 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
а что поменялось ?) 
![image](https://user-images.githubusercontent.com/70904466/217068355-6206ce2d-ab86-4f5e-b62f-e1369d606d8a.png)

2023-02-06 19:39 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
вы должни не дальше его в лево прятать а можете просто display: none сделать в медиа запросе

2023-02-06 19:40 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
также не красива анимация появления будет

2023-02-06 19:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675712770/slider%20one%20foto%20768px.png)

2023-02-06 19:56 UTC, SergeyGlazun requested changes

2023-02-06 19:56 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
> -
![image](https://user-images.githubusercontent.com/70904466/217069255-36ca87d6-a1e0-46d0-aa20-e936cd4c80e3.png)
что то не работает эта штука)

2023-02-06 19:56 UTC, SergeyGlazun commented on src/components/leftbar-burger-menu/leftbar-burger-menu.scss
>      &.closeBookLsts{
![image](https://user-images.githubusercontent.com/70904466/217071391-64797f45-9012-4379-85ba-898a8b6db00c.png)
скролил не работает, да и нужен ли если у вас 4 книги, толи добавьте книг что б скролить их можно было толи не показывайте скрол если книг не достаточно, можете попробовать что ни будь вроде overflow-x: auto

2023-02-07 17:38 UTC, Anastasiya1982 commented on src/components/leftbar-burger-menu/leftbar-burger-menu.scss
>      &.closeBookLsts{
убрала скрол если книг меньше 5 . и он появляется если только  взаимодействуешь с миниатюрами

2023-02-07 17:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675791543/slider%20one%20foto%20768px.png)

2023-02-07 19:15 UTC, SergeyGlazun requested changes

2023-02-07 19:15 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
>  export const BookPreview = ({ imageRoute }) => {
![image](https://user-images.githubusercontent.com/70904466/217341706-67b37550-8554-410a-ba2c-207d00bff993.png)
не все книги работаю из списка

2023-02-07 19:15 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
>    const [thumbsSwiper, setThumbsSwiper] = useState(null);
![image](https://user-images.githubusercontent.com/70904466/217341845-45517177-7f55-43e4-8609-350a7c950367.png)

2023-02-07 19:15 UTC, SergeyGlazun commented on src/components/book-preview/book-preview.jsx
>    const [thumbsSwiper, setThumbsSwiper] = useState(null);
на java когда жать

2023-02-07 19:25 UTC, Anastasiya1982 commented on src/components/book-preview/book-preview.jsx
>    const [thumbsSwiper, setThumbsSwiper] = useState(null);
у меня все нормально не понимаю , при нажатии на что эта ошибка

2023-02-07 19:36 UTC, Anastasiya1982 commented
не понимаю , при нажатии на что эта ошибка

2023-02-07 19:54 UTC, Anastasiya1982 commented
не понимаю , при нажатии на что эта ошибка

2023-02-07 19:56 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675799794/slider%20one%20foto%20768px.png)

2023-02-07 20:04 UTC, Anastasiya1982 commented
да. в json file books  была ошибка

2023-02-07 20:05 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675800344/slider%20one%20foto%20768px.png)

2023-02-07 21:30 UTC, SergeyGlazun approved these changes

2023-02-08 09:29 UTC, merged